version: '3.8'
services:
  chromadb:
    image: chromadb/chroma:latest
    environment:
      - ALLOW_RESET=TRUE
    ports:
      - 8000:8000
    volumes:
      - chroma_data:/chroma/chroma

volumes:
  chroma_data:
    driver: local 